/// Flutter icons AwesomeIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AwesomeIcon
///      fonts:
///       - asset: fonts/AwesomeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AwesomeIcon {
  AwesomeIcon._();

  static const _kFontFam = 'AwesomeIcon';

  static const IconData icon_awesome_hackerrank = IconData(0xe800, fontFamily: _kFontFam);
}
