/// Flutter icons RequestsIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RequestsIcon
///      fonts:
///       - asset: fonts/RequestsIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RequestsIcon {
  RequestsIcon._();

  static const _kFontFam = 'RequestsIcon';

  static const IconData icon_requests = IconData(0xe800, fontFamily: _kFontFam);
}
