/// Flutter icons RequestsAndFriends
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RequestsAndFriends
///      fonts:
///       - asset: fonts/RequestsAndFriends.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RequestsAndFriends {
  RequestsAndFriends._();

  static const _kFontFam = 'RequestsAndFriends';

  static const IconData icon_people = IconData(0xe801, fontFamily: _kFontFam);
}
